// <auto-generated />
using System;
using CGI_Uppgift;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CGI_Uppgift.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210208114340_AddArticleIdMigration")]
    partial class AddArticleIdMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("CGI_Uppgift.Article", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ArticleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ArticleNumber")
                        .HasColumnType("int");

                    b.Property<double>("PricePerUnit")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("Article");
                });

            modelBuilder.Entity("CGI_Uppgift.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("CGI_Uppgift.Orderrow", b =>
                {
                    b.Property<int>("RowNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("ArticleID")
                        .HasColumnType("int");

                    b.Property<int?>("OrderID")
                        .HasColumnType("int");

                    b.HasKey("RowNumber");

                    b.HasIndex("ArticleID");

                    b.HasIndex("OrderID");

                    b.ToTable("Orderrow");
                });

            modelBuilder.Entity("CGI_Uppgift.Orderrow", b =>
                {
                    b.HasOne("CGI_Uppgift.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CGI_Uppgift.Order", null)
                        .WithMany("Orderrow")
                        .HasForeignKey("OrderID");

                    b.Navigation("Article");
                });

            modelBuilder.Entity("CGI_Uppgift.Order", b =>
                {
                    b.Navigation("Orderrow");
                });
#pragma warning restore 612, 618
        }
    }
}
